### ISSUE TITLE
several valid Discover card numbers don't validate

### ISSUE THREAD

**Issue by samuelgoff** [PawelDecowski/jquery-creditcardvalidator#108]
Hello,

I've been provided with several test card numbers from a credit card processing vendor, and they do not validate properly with jquery-creditcardvalidator:

- 6011 0255 0013 6880
- 6011 2023 0012 2430
- 6011 4855 0016 0260
- 6011 7400 0018 6190
- 6011 8699 0013 5410

I've put together a [jsfiddle](https://jsfiddle.net/samuelgoff/dn4f0rwb/11/) to demonstrate the issue.

**Comment by PawelDecowski** [comment]
Hi,

What brand is this supposed to be? And is there a reliable source that confirms those IINs belong to that brand?

Thanks.

**Comment by PawelDecowski** [comment]
Nevermind. Just saw in the title you said Discover. How about a source then?

**Comment by lucasvm** [comment]
I got the same problem card number example: 6011111111111115
Got: Please enter a valid credit card type number.

**Comment by dubcanada** [comment]
Those numbers don't pass Stripe credit card validation. I don't think those are valid numbers.

They also don't pass the Luhn test.
