### ISSUE TITLE
Mastercard added an additional range in 2017

### ISSUE THREAD

**Issue by mkaatman** [PawelDecowski/jquery-creditcardvalidator#120]
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

**Comment by PawelDecowski** [comment]
Already supported: https://github.com/PawelDecowski/jquery-creditcardvalidator/blob/master/jquery.creditCardValidator.coffee#L66

**Comment by mkaatman** [comment]
http://jquerycreditcardvalidator.com/ doesn't seem to support it. I tried typing in: 222100

**Comment by PawelDecowski** [comment]
The demo runs an older version of the plugin before the support for it was added.

It’s on my to-do to update it.
