### ISSUE TITLE
Request - CDNJS Version

### ISSUE THREAD

**Issue by ghost** [PawelDecowski/jquery-creditcardvalidator#122]
Would love to see this on CDNJS!

**Comment by MartinKolarik** [comment]
You can use
https://cdn.jsdelivr.net/gh/PawelDecowski/jquery-creditcardvalidator@1.1.0/jquery.creditCardValidator.js (original file)
or
https://cdn.jsdelivr.net/gh/PawelDecowski/jquery-creditcardvalidator@1.1.0/jquery.creditCardValidator.min.js (minified)

**Comment by PawelDecowski** [comment]
Adding the library to CDNJS is in motion and should happen within the next few days.

**Comment by PawelDecowski** [comment]
[jQuery Credit Card Validator is on CDNJS](https://cdnjs.com/libraries/jquery-creditcardvalidator) now.
