### ISSUE TITLE
2 series Mastercard does not validate

### ISSUE THREAD

**Issue by benjaminjames** [PawelDecowski/jquery-creditcardvalidator#124]
This year Mastercard is issuing new debit cards prefixed with "2" instead of the traditional "5". Currently these are failing to be recognized. Example card number: 2226470000082007 EXP: 10/21 CVC: 153

**Comment by jasongrimes** [comment]
> Mastercard® has received an additional range of 2-series numbers (range 222100-272099) to add to the 5-series (range 510000-559999) that we currently provide.

**Comment by PawelDecowski** [comment]
This has been supported since version 1.1 (November 2016):

https://github.com/PawelDecowski/jquery-creditcardvalidator/blob/v1.1.0/jquery.creditCardValidator.coffee#L66

**Comment by benjaminjames** [comment]
@PawelDecowski Thanks, but is there a reason 2-series cards are not recognized on https://jquerycreditcardvalidator.com/ ?

**Comment by PawelDecowski** [comment]
Yes. The homepage uses an old version of the plugin. I’ll update it soon.
