### ISSUE TITLE
Not valid card shows how valid

### ISSUE THREAD

**Issue by oscarhandsome** [PawelDecowski/jquery-creditcardvalidator#125]
Hello @PawelDecowski and developer.
If somebody knows how to resolve this issue please explain to me?

I have a simple input field.
[Link on the html](http://almall.elbargo.ru/checkout-step-3.html)
[image ](http://almall.elbargo.ru/almall_checkout.jpg) how it works on my dev

My problem is:
I input number, then with regExp is converting to string with after each 4 digits spaces.
and for example, I added this number 4000 0000 0000 0002 from the [main page](https://jquerycreditcardvalidator.com/)
then tried ty change last digit and this is **not valid, - ok**
but i tried to delete last 2-3 digit scipt show that number **is valid**. i don't understand why on the main page the script works, on my example not.

My script I think very simply.
[Code here](http://runkit.com/oscarhandsome/validation-cards)

**Comment by oscarhandsome** [comment]
@PawelDecowski 
I tried your recommendations, both but if delete last 4 digits this all okay
[image](http://almall.elbargo.ru/almall_checkout2.jpg)
but if I deleted 2 last digits this is valid :)
[image](http://almall.elbargo.ru/almall_checkout3.jpg)

i have no idea why it happens...

**Comment by PawelDecowski** [comment]
Visa numbers can be between 13 and 19 digits long. You just happened to end up with a 14 digit long number that has a valid Luhn checksum after removing the last 2 digits. It’s pure chance. Try another number and it’ll most likely fail.

**Comment by oscarhandsome** [comment]
@PawelDecowski 
this depends from a country?

**Comment by oscarhandsome** [comment]
This validator can work with [payfort_fort ](https://github.com/payfort/opencart-payfort/tree/master/upload/catalog/view/javascript/payfort_fort)
I just now, understand that your developed script also there.... awesome!
