### ISSUE TITLE
Delegate instead of bind

### ISSUE THREAD

**Issue by StevenWeathers** [PawelDecowski/jquery-creditcardvalidator#13]
I would like to suggest that the events be refactored from .bind to .delegate (or .on with jQuery 1.7).

Delegate Docs
http://api.jquery.com/delegate/

.On Docs
http://api.jquery.com/on/

**Comment by PawelDecowski** [comment]
This is a breaking change. As of 1.0 required version of jQuery will be 1.7.

**Comment by PawelDecowski** [comment]
This is implemented in just released [1.0](https://github.com/PawelDecowski/jquery-creditcardvalidator/blob/v1.0.0).
