### ISSUE TITLE
validation doesnt work, but why

### ISSUE THREAD

**Issue by halilkoca** [PawelDecowski/jquery-creditcardvalidator#134]
test card no:
5890040000000016 (debit)

**Comment by PawelDecowski** [comment]
It appears you’re right. I’ll look into this.

**Comment by PawelDecowski** [comment]
I confirmed that the library correctly recognises the card as valid.

The demo page (https://jquerycreditcardvalidator.com/) doesn’t, because it uses an old version of the library.
