### ISSUE TITLE
Validator not working for Zokudo cards

### ISSUE THREAD

**Issue by omvaishnav** [PawelDecowski/jquery-creditcardvalidator#135]
I want to allow Zokudo(https://zokudo.com/) cards to validate. How can I enable it? 

Also, it would be great if there is a way to add custom card validation without touching the main file.

**Comment by PawelDecowski** [comment]
> I want to allow Zokudo(https://zokudo.com/) cards to validate. How can I enable it?

Looks like this falls under RuPay brand. I’ll look into adding it in the next version.

> Also, it would be great if there is a way to add custom card validation without touching the main file.

I’m very hesitant about adding this feature because it would discourage people from suggesting adding new card brands to the plugin.

**Comment by omvaishnav** [comment]
Ok, thanks for the reply. I will be looking for a new version with the RuPay brand availability.
