### ISSUE TITLE
use after validation

### ISSUE THREAD

**Issue by faidhim** [PawelDecowski/jquery-creditcardvalidator#136]
Very nice code, what I feel is missing is a simple none tech note to actually explain how to use. i.e. the work flow. e.g. what happens after a card is validated ? In your view, is it then for the payment receiver to log the details and manually process payment or how ?
Thanks

**Comment by PawelDecowski** [comment]
It’s just a validation library. What you do with the credit card number after validation is out of the scope of this library.
