### ISSUE TITLE
is this library still active?

### ISSUE THREAD

**Issue by sachin87** [PawelDecowski/jquery-creditcardvalidator#49]
it was last updated 2 years ago, and many issues are pending, i want to use it in my project confused whether to use it or not?

**Comment by PawelDecowski** [comment]
Hi @sachin87.

Yes, the library is active. As you can see, the “issues” are mostly just feature requests. Any bugs have been fixed almost immediately.

There is a 1.0 in the pipeline which will offer some great new features (see https://github.com/PawelDecowski/jquery-creditcardvalidator/tree/release/1.0 for a sneak peek).

Pawel

**Comment by sachin87** [comment]
in your example website(http://jquerycreditcardvalidator.com/) i think image for american express card is no there, could you add it?

**Comment by PawelDecowski** [comment]
@sachin87 

Sorry, the icons aren’t a part of the library — they’re just there for demo purposes — and as such are not supported. Feel free to use the ones that exist but there are no plans to add any more.
