### ISSUE TITLE
feature/diners_club support

### ISSUE THREAD

**Issue by robertavram** [PawelDecowski/jquery-creditcardvalidator#55]
according to: 
http://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

38520000023237 - is a correct diner's club number...
the regex "3(?:0[0-5]|[68][0-9])[0-9]{11}" seems to do the job, 14 digits.

apparently the card can start with 36 or 38 not only 300-305. 

...Thanks a lot for everything so far. Works great. Maybe just add a 13 digit option for the Visa. :)

**Comment by PawelDecowski** [comment]
Hi @robertavram 

Visa numbers between 13 and 19 characters long will be available in [1.1](https://github.com/PawelDecowski/jquery-creditcardvalidator/milestones/1.1).

I will look into the Diner’s Club numbers.

Thanks for reporting.

**Comment by mac9416** [comment]
More support for this update:
https://www.discovernetwork.com/downloads/IPP_VAR_Compliance.pdf
Apparently the Diner's cards are processed through the Discover network.

**Comment by PawelDecowski** [comment]
I’ve completed this and will include it in [1.2](https://github.com/PawelDecowski/jquery-creditcardvalidator/milestone/3).

I’m aiming to release it tomorrow.

**Comment by PawelDecowski** [comment]
Let me know if this looks right: 89952336aaeba7443c00c05e09e19fafbbe97576
