### ISSUE TITLE
Masking

### ISSUE THREAD

**Issue by custa1200** [PawelDecowski/jquery-creditcardvalidator#57]
An option to automatically add the spaces to the card numbers to reflect the spacing on a credit card, i.e. Visa "4444 1234 1234 1234", AMEX "4747 123456 12345"

**Comment by PawelDecowski** [comment]
This is a validator, not a formatter. There are plenty other tools that will format input fields for you.

**Comment by elijahpaul** [comment]
I'm trying to implement your plugin with the [jQuery-Mask-Plugin](https://github.com/igorescobar/jQuery-Mask-Plugin) for formatting, but am experiencing an odd [issue](https://github.com/igorescobar/jQuery-Mask-Plugin/issues/340) (see - [http://jsfiddle.net/56uscbjv/4/](http://jsfiddle.net/56uscbjv/4/)).

@igorescobar suggested it may be an implementation of your plugin.

I know formatting is not part of your plugin, but I'd appreciate any input you can offer as to why (in this case) the validator is capturing an extra digit despite the mask being complete?

**Comment by PawelDecowski** [comment]
Hi @elijahpaul,

Thanks for reporting the issue.

I’ll try to look into it later today and will get back as soon as I have some results.
