### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined  line:188

### ISSUE THREAD

**Issue by esinanturan** [PawelDecowski/jquery-creditcardvalidator#61]
line 188 : return number.replace(/[ -]/g, '');  
i have got this error , what it might be :S

**Comment by PawelDecowski** [comment]
What’s the error message? So far you only show the line on which some error occurred.

**Comment by esinanturan** [comment]
i use plugin like that 

        $('#account_number').validateCreditCard(function(result) {
            var card_type=result.card_type == null ? '-' : result.card_type.name;

            if(card_type=='mastercard'){
                    $('img.mastercard').removeClass('blur');
                valid();
            }else if(card_type=='visa'){
                    $('img.visa').removeClass('blur');
                valid();

            }else{
                valid();
                $('.card_type').removeClass('blur').addClass('blur')
            }
            function valid(){
                if( (result.valid) && (result.length_valid) && (result.luhn_valid) ){
                    $('.check-valid').show();
                }else{
                    $('.check-valid').hide();
                }
            }

                var card = $(this).val().split(" ").join(""); // remove hyphens
                if (card.length > 0) {
                    card = card.match(new RegExp('.{1,4}', 'g')).join(" ");
                }
                $(this).val(card);

        },{accept:['visa','mastercard']});
it works but on console i got that error Uncaught TypeError: Cannot read property 'replace' of undefined 
and that effects my other functions which comes after that

**Comment by esinanturan** [comment]
any idea ?

**Comment by PawelDecowski** [comment]
I’m not getting any errors using your code: http://codepen.io/paweldecowski/pen/VLBLje

**Comment by esinanturan** [comment]
:S

**Comment by esinanturan** [comment]
so what might be wrong with that :S

**Comment by PawelDecowski** [comment]
What browser are you using?

**Comment by esinanturan** [comment]
chrome

**Comment by PawelDecowski** [comment]
Can you reproduce it here: http://codepen.io/paweldecowski/pen/VLBLje

**Comment by esinanturan** [comment]
i can not :S

**Comment by esinanturan** [comment]
do you think the other plugins can affect this one ? all plugins are in one file

**Comment by PawelDecowski** [comment]
Probably. Can you send me a link to the site?

**Comment by esinanturan** [comment]
how can i send pm on github

**Comment by PawelDecowski** [comment]
Don’t think you can. Email me at pawel@relish.io.

**Comment by esinanturan** [comment]
ok check your mails

**Comment by esinanturan** [comment]
could you find anything ?

**Comment by PawelDecowski** [comment]
The problem is you run validation on all pages, even those that don’t have the `#account_number` element.

Wrap your validation code in a check to make sure the element exists:

```javascript
if ($('#account_number').length) {
    // ...
}
```

**Comment by esinanturan** [comment]
thank you so much

2015-07-16 20:37 GMT+03:00 Pawel Decowski <notifications@github.com>:

**Comment by Webde** [comment]
In reality, this problem, occurred for the time execution library and method. Write 
```javascript
$( document ).ready(function(){
     //Code here
});
 ```

**Comment by oscarhandsome** [comment]
> The problem is you run validation on all pages, even those that don’t have the `#account_number` element.
> 
> Wrap your validation code in a check to make sure the element exists:
> 
> ```js
> if ($('#account_number').length) {
>     // ...
> }
> ```

This is so helped to me because I developed a static view of the form, but on the production backend - devs made automatically generated the form after dom is loaded.
