### ISSUE TITLE
Some Maestro card numbers fail validation

### ISSUE THREAD

**Issue by ksmehra** [PawelDecowski/jquery-creditcardvalidator#64]
in one of our apps, we encountered a particular maestro number which failed the validation. but the same number passes validation at this site (http://www.freeformatter.com/credit-card-number-generator-validator.html)

i can provide the card number for investigation.

**Comment by PawelDecowski** [comment]
Probably not a good idea to post a credit card number online :) Maestro is recognised by the first 4 digits so if you can provide that and the number length, I’ll look into it.

**Comment by ksmehra** [comment]
true! will not put the CC :1234: here :)

starts with
**5892**

**Comment by PawelDecowski** [comment]
This seems to be a valid Maestro card prefix.

According to Wikipedia [Bank card numbers](https://en.wikipedia.org/wiki/Bank_card_number) article, all numbers starting with *58* indicate a Maestro card.

It will be added in v1.1.

**Comment by ksmehra** [comment]
thanks for the pointer. i've fixed the issue in our build. i can send the fix if you'd like, which you can then commit to the mainline.

**Comment by radlws** [comment]
begins with 6304 is both laser and maestro ..  I changed the pattern for maestro as per wikipedia

https://en.wikipedia.org/wiki/Bank_card_number

'^(50|5[6-9]|6[0-9])',
