### ISSUE TITLE
Add Support to Validate Security Code/CCV

### ISSUE THREAD

**Issue by neotropic2023** [PawelDecowski/jquery-creditcardvalidator#66]
Cool script, sadly missing something very crucial, validating the CCV to the credit card number. Or am I missing something and not seeing it anywhere.

**Comment by PawelDecowski** [comment]
You can't validate a CCV beyond checking its length (4 for Amex, 3 for most others). I don't think you need a plugin for that.

**Comment by Tusko** [comment]
$('#cvv').on('keyup', function(){
			var reg, ex, cvv = $(this).val(), cardtype = $('#card-number > input').attr('class');
			if(cardtype === 'amex') {
				reg = /^[0-9]{3,4}$/;
			} else {
				reg = /^[0-9]{3}$/;
			}
			ex = reg.exec(cvv);
			if(ex === null) {
				$(this).addClass('error');
			} else {
				$(this).removeClass('error');
			}
		});

@PawelDecowski

**Comment by pawlik** [comment]
The validation doesn't have to be IN this plugin, but the information about the valid cvv length could. Please see https://github.com/PawelDecowski/jquery-creditcardvalidator/pull/73

**Comment by PawelDecowski** [comment]
@pawlik I suppose it wouldn’t hurt to add it to the `card_types` property. That way it would be available in the `result` object.

**Comment by pawlik** [comment]
messed up branches, here it is: https://github.com/PawelDecowski/jquery-creditcardvalidator/pull/74
