### ISSUE TITLE
RegExp revisiting

### ISSUE THREAD

**Issue by ckorakidis** [PawelDecowski/jquery-creditcardvalidator#68]
Hi,

I just noticed that the regex in some cases seems to be incomplete (e.g. visa).
Please have a look in a few resources regarding the propper regex:
http://stackoverflow.com/questions/9315647/regex-credit-card-number-tests
http://www.regular-expressions.info/creditcard.html

Regards,
Chris

**Comment by PawelDecowski** [comment]
If there are any numbers that fail validation if they shouldn’t, then please post the IIN and a *reliable* source that says it’s valid. Currently the list of IIN prefixes is based on [Wikipedia](https://en.wikipedia.org/wiki/Bank_card_number) and a few other sources.

**Comment by ckorakidis** [comment]
The Wikipedia article you mentioned suggest 13, 16 length for Visa Credit Cards. Please check also the suggested references in the initial message.
Example of 13-digit Visa: 4556781815037
For more valid CC numbers you can use http://www.getcreditcardnumbers.com/

**Comment by PawelDecowski** [comment]
#50 

Like I said, please report **concrete** numbers that don’t work. I don’t have time to go through these websites and test all numbers.

**Comment by ckorakidis** [comment]
I already did it: 4556781815037

**Comment by PawelDecowski** [comment]
And I replied that it’s already planned for next version: #50 

Please read with understanding. Every time I have to clarify something that I’ve already explained, it takes me away from, for example, working on this project.
