### ISSUE TITLE
Clean download JS error

### ISSUE THREAD

**Issue by KevinMcCoy** [PawelDecowski/jquery-creditcardvalidator#69]
Uncaught TypeError: Cannot read property 'replace' of undefined - line 188 jquery.creditCardValidator.js

I'm loading: 
jquery-1.11.3.min.js
jquery-ui-1.11.4/jquery-ui.min.js

then loading: 
jquery.creditCardValidator.js

Get an error on that basic setup.

**Comment by PawelDecowski** [comment]
Duplicate of #61
