### ISSUE TITLE
Add to npm?

### ISSUE THREAD

**Issue by alexiskattan** [PawelDecowski/jquery-creditcardvalidator#70]
Any chance to add this to npm?

**Comment by PawelDecowski** [comment]
Sure. Can’t see why not.

**Comment by AbdullahDahmash** [comment]
1+

**Comment by leith** [comment]
Looks like various forks have been added over the years:
1.0.0 - https://www.npmjs.com/package/jquery-creditcardvalidator (from @PillowPillow)
1.1.1 - https://www.npmjs.com/package/rc-jquery-creditcardvalidator (from @BrunoSalgado)
1.2.2 - https://www.npmjs.com/package/jquery-creditcardvalidator-intervale (from @argumentus)

Is there a timeline on the official one?

**Comment by PawelDecowski** [comment]
Yes! I recently took ownership of the first one and will be publishing v1.2 tomorrow.

**Comment by PawelDecowski** [comment]
[v1.2](https://github.com/PawelDecowski/jquery-creditcardvalidator/releases/tag/v1.2.0) is out and it’s officially on npm:

https://www.npmjs.com/package/jquery-creditcardvalidator

```
npm i jquery-creditcardvalidator
```
