### ISSUE TITLE
ie11 compatibility issue

### ISSUE THREAD

**Issue by italomandara** [PawelDecowski/jquery-creditcardvalidator#77]
ie11 - windows8
Method get_card_type returns always null, preventing to detect the card type

commenting the lines below seems to fix the problem
```js
this.on('input.jccv', (function(_this) {
  return function() {
    $(_this).off('keyup.jccv');
    return callback.call(_this, validate());
  };
})(this));
```

**Comment by PawelDecowski** [comment]
You mean commenting out the lines above fixes a problem with `get_card_type()` method? This makes no sense. I will have to test it but I don’t have Windows 8 so will have to download a VirtualBox image (meaning it will take some time).

If you could provide more details that would definitely speed things up.

Thanks for reporting!

**Comment by italomandara** [comment]
Yes, basically the problem is not in get_card_type, is what you pass to that method, looks like ie11 is not able to get the input value unless you comment that part

**Comment by italomandara** [comment]
It's not your code, you can close the issue. the problem was the document ready function wasn't wrapping the initialisation function. worked well on other browsers, that's interesting.

**Comment by PawelDecowski** [comment]
No worries! Glad you figured it out.
