### ISSUE TITLE
Elo support

### ISSUE THREAD

**Issue by cauealvesbraz** [PawelDecowski/jquery-creditcardvalidator#82]
Any idea of having support for `ELO Credit Card`?

**Comment by PawelDecowski** [comment]
I’ll look into it for v1.2

**Comment by ceasbz** [comment]
@PawelDecowski If need any help, let me know. :)

**Comment by PawelDecowski** [comment]
@ceasbz Do you have any sources that provide IIN ranges? I can’t find anything reliable.

**Comment by ceasbz** [comment]
@PawelDecowski Yes, see here: https://github.com/jessepollak/payment/issues/27 this table are updated with the last version :)

**Comment by PawelDecowski** [comment]
This is just a comment by you on another project. Not that I don’t trust you ;) but where did you get the list from?

**Comment by ceasbz** [comment]
@PawelDecowski Here in our company, we use the ELO Payment. And every update, I receive a table with the current IIN ranges. :)

**Comment by PawelDecowski** [comment]
OK. As long as they don’t collide with other cards, I’ll add them.

**Comment by ceasbz** [comment]
I am searching where is the documentation about that.
Em qua, 19 de out de 2016 às 12:25, Pawel Decowski <notifications@github.com>
escreveu:

**Comment by ceasbz** [comment]
@PawelDecowski I am searching where is the documentation about that. :)

**Comment by PawelDecowski** [comment]
Are ELO card numbers Luhn-validated? According to [this](https://github.com/Fivell/credit_card_validations/blob/bf5ddfed273ce7aed8b5b453845e83ac467e654f/lib/data/brands.yaml#L276), they’re not.

**Comment by ttibau** [comment]
Please, add support do ELO! <3

**Comment by ceasbz** [comment]
Hey @PawelDecowski sorry for delay.

I don't remember about that, do you have any progress?

**Comment by mateuspadua** [comment]
@ceasbz If you still need this, follow the solution just below. Valeuuuuu :)

....
,{
        name: 'aura',
        range: '5078',
        valid_length: [19]
      }, {
        name: 'elo',
        range: '4011, 401178, 401179, 431274, 438935, 451416, 457393, 4576, 457631, 457632, ' + 
               '504175, 506699-506778, 509000-509999, ' + 
               '627780, 636297, 636368, 636369, ' + 
               '650031-650033, 650035-650051, 650405-650439, 650485-650538, 650541-650598, 650700-650718, 650720-650727, 650901-650920, 651652-651679, 655000-655019, 655021-655058',
        valid_length: [16]
      }, {  // aura and elo must inserted above visa_electron
        name: 'visa_electron',
        range: '4026, 417500, 4508, 4844, 4913, 4917',
        valid_length: [16]
      },
...

**Comment by ceasbz** [comment]
Ty @mateuspadua

**Comment by mateuspadua** [comment]
:)

**Comment by nelsongustavo** [comment]
@mateuspadua Como vc alterou esse json? Obrigado.

**Comment by PawelDecowski** [comment]
I’m hesitant to add this as these ranges collide with Maestro and Visa. I’m closing it until someone can show a reliable source of IINs.
