### ISSUE TITLE
Credit vs Debit cards

### ISSUE THREAD

**Issue by ubiquitas** [PawelDecowski/jquery-creditcardvalidator#85]
any plans to differentiate between the two - UK user here and it's needed

also I think Maestro no longer requires start date / issue number - here in the UK at least

**Comment by PawelDecowski** [comment]
I don’t think there’s a way to tell if a card is a debit or credit based on NIN. It’s difficult enough to find NIN ranges for different brands.

The validator has nothing to do with start date or issue number. It’s just a demo form.

**Comment by ubiquitas** [comment]
thanks for rapid reply :)

I guess I can ask user if it's debit or credit as part of my checkout

**Comment by alexhansford** [comment]
Currently Barclaycard provides a list of debit/credit BIN ranges here: https://www.barclaycard.co.uk/business/accepting-payments/bin-range (see the attached spreadsheet for UK debit ranges)

It would be helpful to indicate whether the card presented looks like a Debit or Credit card number - but I wouldn't recommend validating against this as the list is never perfect.

**Comment by ubiquitas** [comment]
thanks Alex - turned out my payment gateway (SagePay) don't require debit cards to be marked any differently to credit cards. So I can present my customers with a simple Visa, Mastercard, Maestro choice.
Hopefully 1.1 is released soon with more recent BIN changes as I've held off implementing this validator as yet.

**Comment by PawelDecowski** [comment]
@ubiquitas 1.1 has been released
