### ISSUE TITLE
Use Gulp or Grunt instead of CodeKit

### ISSUE THREAD

**Issue by PawelDecowski** [PawelDecowski/jquery-creditcardvalidator#88]
CodeKit’s config file doesn’t play nice with changing branches. It updates every time you switch a branch and often causes conflicts.

**Comment by ceasbz** [comment]
@PawelDecowski Maybe [gulp](http://gulpjs.com/)? Is more fast :)

**Comment by PawelDecowski** [comment]
@ceasbz Good suggestion. Will consider. Changed title accordingly.

**Comment by PawelDecowski** [comment]
The only thing is, I implemented Grunt last night.

I wouldn’t mind having both, so users can choose. The problem is grunt-coffee uses CoffeeScript 1.10, whereas gulp-coffee uses CoffeeScript 1.11.1 (at the time of writing this comment). I don’t like the idea of people overwriting the JS file just because they compiled it using a different version of CoffeeScript so it produced different code. I understand this can happen with just Grunt or just Gulp (or even CodeKit) as it entirely depends on which version they’re using (which determines the version of CS) but I think allowing multiple task runners would make it worse.

Thoughts?

I _am_ leaning towards Gulp, so, unless there are any objections, I _think_ that’s what I’ll start using in v1.2.

**Comment by PawelDecowski** [comment]
Gulp has been implemented in v1.2 and will be released soon.
