### ISSUE TITLE
New MasterCard BIN Series Numbers

### ISSUE THREAD

**Issue by lucasisola** [PawelDecowski/jquery-creditcardvalidator#91]
MasterCard is introducing a new Bank Identification Number (BIN) series that begins with 2. This new series **(222100–272099)** will be processed the same way as the existing 51-55 BIN series today.

MasterCard expects the 2-series BINs to be completely supported no later than October 14, 2016. Issuance of cards in this new series is not expected until the first quarter of 2017.

Some test credit card numbers we're already seeing circulated that aren't recognized upon entry.
2223000010309703
2223000010309711

**Comment by PawelDecowski** [comment]
Already supported: https://github.com/PawelDecowski/jquery-creditcardvalidator/blob/master/jquery.creditCardValidator.coffee#L66

**Comment by lucasisola** [comment]
@PawelDecowski So awesome of you to reply so quick!! I noticed though that the demo page you have setup isn't displaying the MasterCard logo for this new BIN...

See screencast: http://recordit.co/L5JZTBXJGJ

**Comment by PawelDecowski** [comment]
Looks like the demo page still uses 1.0. The new MasterCard range was added in 1.1. I could swear I updated it. I’ll try to find time to fix it tomorrow.

**Comment by lucasisola** [comment]
@PawelDecowski No sweat!! I think that was the problem with our app too. We're using 1.0.

Thanks for the reply. Cheers, Lucas
