### ISSUE TITLE
MasterCard EMV Support

### ISSUE THREAD

**Issue by Romanulus** [PawelDecowski/jquery-creditcardvalidator#93]
As per the new BINs coming out from MasterCard:
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

I have been using a really simple pattern (for purposes on the UI):
`/^[2]\d{1}/`

However, I have seen some more thorough versions out there, ala:
`/^5[1-5]\d{2}-?\d{4}-?\d{4}-?\d{4}$|^2(?:2(?:2[1-9]|[3-9]\d)|[3-6]\d\d|7(?:[01]\d|20))-?\d{4}-?\d{4}-?\d{4}$/`

Will this support be added sometime soon?

**Comment by PawelDecowski** [comment]
Sooner than you think. So soon, that it’s already supported in [v1.1](https://github.com/PawelDecowski/jquery-creditcardvalidator/releases/tag/v1.1.0) ;)\

**Comment by Romanulus** [comment]
ZOMG... Thanks. :)
Way to RTFM!
