### ISSUE TITLE
update regex for credit card for example for mastercard

### ISSUE THREAD

**Issue by kichawa** [PawelDecowski/jquery-creditcardvalidator#95]
example:

https://github.com/jessepollak/card/blob/master/dist/jquery.card.js#L1095

**Comment by PawelDecowski** [comment]
I have no idea what you mean. Can you clarify?

**Comment by alpharder** [comment]
Beginning in 2017, MasterCard cards will also be issued with account numbers beginning with a “2”. The cards beginning with a 2 will be processed in the same manner as current MasterCard cards. 
MasterCard requires that all point-of-sale systems accepting the current 5 series cards must also be able to accept the cards with the new 2 series number.

**Comment by PawelDecowski** [comment]
Mastercard `2` series cards have been supported since version 1.1, which was released in October 2016.

**Comment by alpharder** [comment]
@PawelDecowski Wow, missed this in changelog. Thanks!

**Comment by alpharder** [comment]
@PawelDecowski Unfortunately, the existing code doesn't actually solve the problem as the `2223000048400011` card number is not being detected as Mastercard.

**Comment by PawelDecowski** [comment]
![image](https://cloud.githubusercontent.com/assets/657678/23856072/0dbc59ce-07f0-11e7-8048-1c58bb5435ab.png)

This is from the example code in the repo.

**Comment by alpharder** [comment]
@PawelDecowski that was my fault, sorry. Code works excellent.

**Comment by PawelDecowski** [comment]
👍
