### ISSUE TITLE
Can you add license file to porject?

### ISSUE THREAD

**Issue by yuxiaomin** [PawelDecowski/jquery-creditcardvalidator#96]
In changelog you mentioned that it is MIT license. But it's better that you can include a license file in the project root folder.

**Comment by PawelDecowski** [comment]
Will add it in [v1.2)[https://github.com/PawelDecowski/jquery-creditcardvalidator/milestone/3]

**Comment by PawelDecowski** [comment]
Done in [v1.2](https://github.com/PawelDecowski/jquery-creditcardvalidator/milestone/3). Will be release shortly.
